[package]
name = "minilisp"
version = "0.1.0"
authors = ["Andreas H. Klostergaard <akl@klostergaard.net>"]
edition = "2018"

[features]
vm-debug = ["backtrace"]

[dependencies]
assert_matches = "1.3"
rustyline = "5.0"
backtrace = { version = "0.3.40", optional = true }
